# Generated by Django 3.2.10 on 2022-01-03 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('student_id', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
