# Generated by Django 3.2.10 on 2022-01-09 10:16

import django.core.validators
from django.db import migrations, models
import fg.models


class Migration(migrations.Migration):

    dependencies = [
        ('fg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fg',
            managers=[
                ('objects', fg.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='fg',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='fg',
            name='password',
            field=models.CharField(default=None, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fg',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='fg',
            name='student_id',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
