# Generated by Django 3.2.10 on 2022-01-03 17:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freshman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('register', models.BooleanField(default=False)),
                ('department', models.CharField(max_length=30, null=True)),
                ('sex', models.CharField(max_length=10, null=True)),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.lc')),
            ],
            options={
                'db_table': 'freshman',
                'ordering': ['lc', 'name'],
            },
        ),
    ]
