# Generated by Django 3.2.10 on 2022-01-05 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshman',
            name='sex',
        ),
        migrations.AddField(
            model_name='freshman',
            name='student_id',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='freshman',
            name='phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
